name: post

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * 1'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Configure Python with pip cache
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Post
      env:
        TOOT_CONFIG: ${{ secrets.MASTODON_TOOT_CONFIG }}
      run: |-
        mkdir -p ~/.config/toot
        echo $TOOT_CONFIG > ~/.config/toot/config.json
        toot post "monday" \
          --media ./monday.mp4 --description "undertale-style video of roast chicken going around, leaving a small trail behind. eventually it ends up at a sign which reads: monday." --visibility public
